# Generated by Django 5.1.6 on 2025-02-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutualfund',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='rank',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='mutualfund',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
