# Generated by Django 5.1.6 on 2025-02-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualfunds', '0002_alter_mutualfund_options_mutualfund_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
